version: '3.9'

services:
  bmg_app:
    container_name: bmg_app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresdb:5432/postgres
    depends_on:
      - postgresdb, redis_bmg

  postgresdb:
    container_name: postgresdb
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_bmg
    command: redis-server
    ports:
     - '6379:6379'
  
  celery:
    build: .
    container_name: celery_bmg
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresdb:5432/postgres
    command: celery -A run.celery worker --pool=gevent --concurrency=100 --loglevel=info
    depends_on:
      - redis_bmg
  
  
volumes:
  pgdata: {}
